/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bu/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Active SBU catalogue products, including zero-stock items. BU_MANAGER and UNIT_STAFF are scoped to their authenticated profile. Privileged roles must supply sbu_id. Cursor order is (name, id). */
        get: operations["searchSbuCatalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfer-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransferRequests"];
        put?: never;
        post: operations["createTransferRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/return-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReturnRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogueProduct: {
            /** Format: uuid */
            id: string;
            name: string;
            sku: string;
            uom: string;
            unit_cost: number | null;
            stock_quantity: number;
        };
        CataloguePage: {
            items: components["schemas"]["CatalogueProduct"][];
            nextCursor: string | null;
            hasMore: boolean;
        };
        CreateTransferRequest: {
            /** Format: uuid */
            requesting_unit_id: string;
            /** Format: date */
            required_date?: string | null;
            notes?: string | null;
            lines: components["schemas"]["TransferRequestLineInput"][];
        };
        TransferRequestLineInput: {
            /** Format: uuid */
            product_id: string;
            requested_quantity: number;
        };
        ReferenceResponse: {
            /** Format: uuid */
            id: string;
            reference_number: string;
        };
        TransferRequest: {
            /** Format: uuid */
            id: string;
            reference_number: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        ReturnRequest: {
            /** Format: uuid */
            id: string;
            reference_number: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        Notification: {
            id: string;
            type: string;
            message: string;
            is_read: boolean;
            related_entity_id?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchSbuCatalogue: {
        parameters: {
            query?: {
                search?: string;
                limit?: number;
                /** @description Opaque continuation token, bound to SBU and search. */
                cursor?: string;
                sbu_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded catalogue page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CataloguePage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid account SBU assignment */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Catalogue retrieval failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTransferRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transfer requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferRequest"][];
                };
            };
        };
    };
    createTransferRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransferRequest"];
            };
        };
        responses: {
            /** @description Created transfer request */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications for the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    listReturnRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnRequest"][];
                };
            };
        };
    };
}
