import type { Metadata } from "next";
import { Inter  } from "next/font/google";
import "./globals.css";
import AuthGuard from "@/components/AuthGuard";

const publicSans = Inter({
  variable: "--font-public-sans",
  subsets: ["latin"],
  // weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthGuard />
        {children}
      </body>
    </html>
  );
}
