/**
 * seed_prod.ts — Production seed script for HGL-WMS
 *
 * What it does:
 *   1. Deletes ALL existing auth users + clears all application tables
 *   2. Seeds the required SBUs
 *   3. Seeds the required users with their roles
 *   4. Seeds warehouse inventory ONLY for LABAMBAM, JARA, and HARVEST RETAIL
 *      from the attached CSV stock-count reports (data hard-coded below)
 *
 * Default password for all accounts: Demo@1234!
 *
 * Run:  npx tsx scripts/seed/seed_prod.ts
 * Requires SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY in .env
 */
import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = (process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL)!;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !serviceRoleKey) {
  console.error(
    "SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY must be set",
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey, {
  auth: { persistSession: false },
});

const DEFAULT_PASSWORD = "Demo@1234!";

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function createUser(
  email: string,
  fullName: string,
  role: string,
  sbuId: string | null,
  unitId: string | null = null,
): Promise<string> {
  const { data, error } = await supabase.auth.admin.createUser({
    email,
    password: DEFAULT_PASSWORD,
    email_confirm: true,
    user_metadata: { role, full_name: fullName, sbu_id: sbuId, unit_id: unitId },
  });
  if (error) throw new Error(`createUser ${email}: ${error.message}`);

  await supabase.from("profiles").insert({
    id: data.user.id,
    full_name: fullName,
    role,
    sbu_id: sbuId,
    unit_id: unitId,
    is_active: true,
  });

  console.log(`    + created  ${email}  (${role})`);
  return data.user.id;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  // ── STEP 0: Wipe everything ────────────────────────────────────────────────
  console.log("\n[0] Clearing database…");

  // Delete all auth users first
  const { data: userList } = await supabase.auth.admin.listUsers({ perPage: 1000 });
  const users = userList?.users ?? [];
  for (const u of users) {
    await supabase.auth.admin.deleteUser(u.id);
  }
  console.log(`  Deleted ${users.length} auth user(s)`);

  // Delete application table data in FK-safe dependency order (deepest children first).
  const ZERO = "00000000-0000-0000-0000-000000000000";
  const uuidTables = [
    "damage_recalls", // FK → damage_ledger, supplier_grn_line_items
    "stock_losses", // FK → variance_dispositions
    "damage_ledger", // FK → variance_proposal_lines
    "variance_dispositions", // FK → grn_line_items, grns
    "variance_proposal_lines", // FK → variance_proposals, grn_line_items
    "grn_line_items", // FK → grns, products
    "variance_proposals", // FK → transfer_requests
    "grns", // FK → transfer_requests
    "supplier_grn_line_items", // FK → supplier_grns, products
    "supplier_grns", // FK → sbus
    "intra_warehouse_transfers",
    "issuance_line_items", // FK → issuances, products
    "issuances", // FK → transfer_requests
    "return_line_items", // FK → return_requests, products
    "return_requests", // FK → sbus, transfer_requests
    "transfer_line_items", // FK → transfer_requests, products
    "transaction_documents", // FK → transfer_requests
    "expiry_ledger", // FK → products
    "transfer_requests", // FK → sbus, sbu_units
    "products",
    "audit_logs",
    "notifications",
    "profiles", // usually already gone via auth user cascade
    "sbu_units", // FK → sbus
    "sbus",
  ];
  for (const t of uuidTables) {
    const { error } = await supabase.from(t).delete().gte("id", ZERO);
    if (error) console.warn(`  Warning: could not clear ${t}: ${error.message}`);
  }
  // sbu_settings uses sbu_id as its PK (no `id` column)
  await supabase.from("sbu_settings").delete().gte("sbu_id", ZERO);
  console.log("  Tables cleared");

  // ── STEP 1: SBUs ──────────────────────────────────────────────────────────
  console.log("\n[1] Seeding SBUs…");
  const sbuDefs = [
    { name: "Jara Retail FMCG Store", code: "JARA" },
    { name: "Grand Access Pharmaceuticals", code: "GRAX" },
    { name: "Bounty Wholesale", code: "BNTY" },
    { name: "Labambam", code: "LBMB" },
    { name: "HGC Logistics Company", code: "HGCT" },
    { name: "Harvest Retail Filling Station Chain", code: "HRFS" },
  ];

  const { data: sbuData, error: sbuError } = await supabase
    .from("sbus")
    .upsert(sbuDefs, { onConflict: "code" })
    .select();
  if (sbuError) throw sbuError;

  const sbuMap: Record<string, string> = {};
  for (const s of sbuData ?? []) sbuMap[s.code] = s.id;
  console.log(`  Created ${sbuData?.length ?? 0} SBUs`);

  // ── STEP 2: Users ──────────────────────────────────────────────────────────
  console.log("\n[2] Seeding users…");

  // ADMIN
  await createUser("grace.usoro@harvestgl.net", "Grace Usoro", "ADMIN", null);

  // WAREHOUSE_MANAGER
  await createUser("chinedu.ewuzie@harvestgl.net", "Ewuzie Chinedu", "WAREHOUSE_MANAGER", null);

  // FINANCE_MANAGER (three accounts)
  await createUser("prince.don-ibeh@harvestgl.net", "Prince Don-Ibeh", "FINANCE_MANAGER", null);
  await createUser("chinwe@harvestgl.net", "Chinwendu Gozie-Nwachukwu", "FINANCE_MANAGER", null);
  await createUser("iberedem.ikwo@harvestgl.net", "Iberedem Ikwo", "FINANCE_MANAGER", null);

  // BU_MANAGERs — linked to their SBUs
  await createUser("bisi@harvestgl.net", "Olabisi Popoola", "BU_MANAGER", sbuMap["BNTY"]);
  await createUser(
    "oghenetejiri.edje@harvestgl.net",
    "Oghenetejiri Edje",
    "BU_MANAGER",
    sbuMap["JARA"],
  );
  await createUser("ugou@harvestgl.net", "Ugo Utoh", "BU_MANAGER", sbuMap["LBMB"]);
  await createUser("esomchi.uche@harvestgl.net", "Esomchi Uche", "BU_MANAGER", sbuMap["HGCT"]);
  await createUser("Chigozie@harvestgl.net", "Chigozie Nwachukwu", "BU_MANAGER", sbuMap["GRAX"]);
  await createUser(
    "newlife@harvestgl.net",
    "Newlife Ogheneruemu Egbona",
    "BU_MANAGER",
    sbuMap["HRFS"],
  );
  await createUser("kingsley@harvestgl.net", "Kingsley Utoh", "BU_MANAGER", sbuMap["HRFS"]);

  console.log("  All users created");

  // ── STEP 3: Products ───────────────────────────────────────────────────────
  console.log("\n[3] Seeding products…");

  // ─────────────────────────────────────────────────────────────────────────
  // JARA — from "JARA LH WAREHOUSE ITEM MGT REPORT - JARA ITEM SUMMARY.csv"
  // Only items with Stock Balance > 0 are included
  // ─────────────────────────────────────────────────────────────────────────
  const jaraProducts = [
    // Shelving fixtures (bay G1)
    {
      name: "Shelf Hanger 900/400 + 900/350 X 50",
      sku: "JARA-SHF-001",
      unit_of_measure: "pc",
      stock_quantity: 3250,
      low_stock_threshold: 163,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "A11 Shelf Layers 900/400 + 900/350 X 8",
      sku: "JARA-SHF-002",
      unit_of_measure: "pc",
      stock_quantity: 5408,
      low_stock_threshold: 270,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "A11 Shelf Layers 900/200 X 8",
      sku: "JARA-SHF-003",
      unit_of_measure: "pc",
      stock_quantity: 336,
      low_stock_threshold: 17,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 Shelf Parts 900/20 X 8 +2Pcs",
      sku: "JARA-SHF-004",
      unit_of_measure: "pc",
      stock_quantity: 322,
      low_stock_threshold: 16,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B18 Shelf Stands Heads 1550/400 X 4",
      sku: "JARA-SHF-005",
      unit_of_measure: "pc",
      stock_quantity: 460,
      low_stock_threshold: 23,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Shelf Stand 705/18",
      sku: "JARA-SHF-006",
      unit_of_measure: "pc",
      stock_quantity: 828,
      low_stock_threshold: 41,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B18/400 Shelf Stand Small Single Heads + 192Pcs",
      sku: "JARA-SHF-007",
      unit_of_measure: "pc",
      stock_quantity: 812,
      low_stock_threshold: 41,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "A11 Slim Shelf Hooks 1550/50 X 50",
      sku: "JARA-SHF-008",
      unit_of_measure: "pc",
      stock_quantity: 2550,
      low_stock_threshold: 128,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Short Shelf Stand X 4",
      sku: "JARA-SHF-015",
      unit_of_measure: "pc",
      stock_quantity: 384,
      low_stock_threshold: 19,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Long Shelf Stand X 4",
      sku: "JARA-SHF-016",
      unit_of_measure: "pc",
      stock_quantity: 122,
      low_stock_threshold: 6,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Back Panel Small Size X 8",
      sku: "JARA-SHF-017",
      unit_of_measure: "pc",
      stock_quantity: 122,
      low_stock_threshold: 6,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Back Panel Big Size X 8",
      sku: "JARA-SHF-018",
      unit_of_measure: "pc",
      stock_quantity: 264,
      low_stock_threshold: 13,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Back Panel Medium X 8",
      sku: "JARA-SHF-019",
      unit_of_measure: "pc",
      stock_quantity: 251,
      low_stock_threshold: 13,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Side Shelf Cover Small Size",
      sku: "JARA-SHF-020",
      unit_of_measure: "pc",
      stock_quantity: 89,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Side Shelf Cover Long",
      sku: "JARA-SHF-021",
      unit_of_measure: "pc",
      stock_quantity: 255,
      low_stock_threshold: 13,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B18/400 X 4 +29",
      sku: "JARA-SHF-022",
      unit_of_measure: "pc",
      stock_quantity: 737,
      low_stock_threshold: 37,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 Shelf Hook 350 X 80 +49Pcs",
      sku: "JARA-SHF-023",
      unit_of_measure: "pc",
      stock_quantity: 6032,
      low_stock_threshold: 302,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Shelf Foot",
      sku: "JARA-SHF-024",
      unit_of_measure: "pc",
      stock_quantity: 84,
      low_stock_threshold: 4,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 900/40 X 40",
      sku: "JARA-SHF-025",
      unit_of_measure: "pc",
      stock_quantity: 400,
      low_stock_threshold: 20,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 900/20 X 20",
      sku: "JARA-SHF-026",
      unit_of_measure: "pc",
      stock_quantity: 1040,
      low_stock_threshold: 52,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 800/18 X 18",
      sku: "JARA-SHF-027",
      unit_of_measure: "pc",
      stock_quantity: 108,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B18 900/40",
      sku: "JARA-SHF-028",
      unit_of_measure: "pc",
      stock_quantity: 68,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 800/20",
      sku: "JARA-SHF-029",
      unit_of_measure: "pc",
      stock_quantity: 60,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 800/40",
      sku: "JARA-SHF-030",
      unit_of_measure: "pc",
      stock_quantity: 120,
      low_stock_threshold: 6,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "B12 350/20",
      sku: "JARA-SHF-031",
      unit_of_measure: "pc",
      stock_quantity: 1540,
      low_stock_threshold: 77,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Side Shelf Holder Short",
      sku: "JARA-SHF-032",
      unit_of_measure: "pc",
      stock_quantity: 18,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Ladder
    {
      name: "Ladder X 3",
      sku: "JARA-LDR-001",
      unit_of_measure: "unit",
      stock_quantity: 18,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Price tags
    {
      name: "Price Tag Holder X 200 +90Pcs",
      sku: "JARA-TAG-001",
      unit_of_measure: "pc",
      stock_quantity: 2090,
      low_stock_threshold: 105,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Chillers & Freezers (bay G2)
    {
      name: "Open Chiller Big Size",
      sku: "JARA-CHL-001",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Open Chiller Small Size",
      sku: "JARA-CHL-002",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Supermarket Chiller 2 Doors",
      sku: "JARA-CHL-003",
      unit_of_measure: "unit",
      stock_quantity: 37,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Supermarket Chiller 3 Doors",
      sku: "JARA-CHL-004",
      unit_of_measure: "unit",
      stock_quantity: 49,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Supermarket Chiller 4 Doors",
      sku: "JARA-CHL-005",
      unit_of_measure: "unit",
      stock_quantity: 32,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Supermarket Chiller 1 Door",
      sku: "JARA-CHL-006",
      unit_of_measure: "unit",
      stock_quantity: 26,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Jara Chiller 2 Doors",
      sku: "JARA-CHL-007",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Jara Chiller 3 Doors",
      sku: "JARA-CHL-008",
      unit_of_measure: "unit",
      stock_quantity: 29,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Jara Chiller 4 Doors",
      sku: "JARA-CHL-009",
      unit_of_measure: "unit",
      stock_quantity: 14,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Nameless Chiller 4 Doors Up And Down",
      sku: "JARA-CHL-010",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Nameless Chiller 2 Doors",
      sku: "JARA-CHL-011",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Chiller 2500",
      sku: "JARA-CHL-012",
      unit_of_measure: "unit",
      stock_quantity: 30,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Chiller 1900",
      sku: "JARA-CHL-013",
      unit_of_measure: "unit",
      stock_quantity: 37,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Ugur Big Chillers",
      sku: "JARA-CHL-014",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Old Model Jara Chillers",
      sku: "JARA-CHL-015",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Danone Display Fridge",
      sku: "JARA-CHL-016",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // HARVEST RETAIL — from "HARVEST-LH STOCK RECORD - Harvest STOCK SUMMARY.csv"
  // Only items with Stock Balance > 0 are included
  // ─────────────────────────────────────────────────────────────────────────
  const harvestProducts = [
    // Freezers & cold rooms (bay J1)
    {
      name: "Artificial Trees",
      sku: "HRFS-006",
      unit_of_measure: "unit",
      stock_quantity: 15,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Island Freezer UGA",
      sku: "HRFS-007",
      unit_of_measure: "unit",
      stock_quantity: 23,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "UGA Freezer",
      sku: "HRFS-008",
      unit_of_measure: "unit",
      stock_quantity: 14,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Cold Room (TS-021050/N)",
      sku: "HRFS-009",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Senol Cold Room (M040-K03)",
      sku: "HRFS-010",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Copper Pipe",
      sku: "HRFS-011",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Senol Cold Room Accessories",
      sku: "HRFS-012",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Industrial Pumps",
      sku: "HRFS-005",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "REFR Cooling Machine Hanging Type (BG-060GL-E5)",
      sku: "HRFS-019",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Ergonomic Office Chair",
      sku: "HRFS-094",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    {
      name: "Indoor Cycling Machine (D525XMO1)",
      sku: "HRFS-095",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J1",
    },
    // Chillers (bay K1)
    {
      name: "Ugur Chiller (100004919487)",
      sku: "HRFS-004",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "K1",
    },
    // Fuel dispensers (bay H1)
    {
      name: "Fuel Dispenser (C552J6361G)",
      sku: "HRFS-001",
      unit_of_measure: "unit",
      stock_quantity: 12,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "H1",
    },
    {
      name: "Fuel Dispenser Submersible Type",
      sku: "HRFS-002",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H1",
    },
    {
      name: "Fuel Dispenser 6 in 1 Pump",
      sku: "HRFS-003",
      unit_of_measure: "unit",
      stock_quantity: 23,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "H1",
    },
    {
      name: "Fuel Dispenser 2 in 1",
      sku: "HRFS-020",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H1",
    },
    // Air conditioners (bay I1)
    {
      name: "Air Conditioner Outdoor Unit (AUW-48UT25H/Hisense)",
      sku: "HRFS-013",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Air Conditioner Outdoor Unit (AUW-36UT25N/Hisense)",
      sku: "HRFS-014",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Cassette Air Conditioner Indoor (CQ4N-XMI365)",
      sku: "HRFS-015",
      unit_of_measure: "unit",
      stock_quantity: 26,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Cassette Air Conditioner Indoor (CQ4N-XM1245)",
      sku: "HRFS-016",
      unit_of_measure: "unit",
      stock_quantity: 15,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Four-Way Cassette Air Conditioner (T-MBQ4-04B)",
      sku: "HRFS-017",
      unit_of_measure: "unit",
      stock_quantity: 19,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Four-Way Cassette Air Conditioner (CQ4N-XMI365)",
      sku: "HRFS-018",
      unit_of_measure: "unit",
      stock_quantity: 25,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Industrial Pumps Standing Type",
      sku: "HRFS-022",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Brown Plywood Metal Frame",
      sku: "HRFS-028",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Plywood Frame",
      sku: "HRFS-030",
      unit_of_measure: "unit",
      stock_quantity: 31,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Plywood Board Reddish Brown",
      sku: "HRFS-031",
      unit_of_measure: "unit",
      stock_quantity: 18,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I1",
    },
    {
      name: "Wooden Panel",
      sku: "HRFS-033",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I1",
    },
    // Pumps & industrial (bay J2)
    {
      name: "Industrial Rod",
      sku: "HRFS-023",
      unit_of_measure: "unit",
      stock_quantity: 5,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Accessories for Industrial Pumps",
      sku: "HRFS-024",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    // Lighting (bay J2)
    {
      name: "LED Light (59x36x29cm)",
      sku: "HRFS-037",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Lifting Touch Warm Light (98x25x39cm)",
      sku: "HRFS-038",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Circular LED Light Circuit",
      sku: "HRFS-039",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Circular LED Light (58x45x59cm)",
      sku: "HRFS-040",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "R5-54 LED Light (82x68x36cm)",
      sku: "HRFS-041",
      unit_of_measure: "unit",
      stock_quantity: 126,
      low_stock_threshold: 13,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "R3-45 LED Light (82x68x36cm)",
      sku: "HRFS-042",
      unit_of_measure: "unit",
      stock_quantity: 54,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "R2-30 LED Light (82x68x37cm)",
      sku: "HRFS-043",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "LED Light Panels",
      sku: "HRFS-044",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 8053 Long+Tail (118x82x15cm)",
      sku: "HRFS-045",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 8013 Tmall Voice (118x82x15cm)",
      sku: "HRFS-046",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 9061 Tmall Voice+ (118x82x15cm)",
      sku: "HRFS-047",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 8026 Tmall Voice (118x82x15cm)",
      sku: "HRFS-048",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 8032 Tmall Voice (118x82x15cm)",
      sku: "HRFS-049",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "3-Colour LED Light 8113 Small Square (118x82x15cm)",
      sku: "HRFS-050",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Post-Modern Pendant Lamp 2126 (66x54x41cm)",
      sku: "HRFS-051",
      unit_of_measure: "unit",
      stock_quantity: 18,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "LED Strip Light (868x350mm)",
      sku: "HRFS-052",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "LED Big Light (74.5x30x46.5cm)",
      sku: "HRFS-053",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "LED Light R2-30 (68x58x35cm)",
      sku: "HRFS-054",
      unit_of_measure: "unit",
      stock_quantity: 23,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Wall Washer Light (53x22x52cm)",
      sku: "HRFS-055",
      unit_of_measure: "unit",
      stock_quantity: 12,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Universal Floor Socket (MD-5-CO5W)",
      sku: "HRFS-056",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "Flood Light (MR01P-5570200W)",
      sku: "HRFS-057",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    {
      name: "PVC Electrical Tape (1000mm)",
      sku: "HRFS-032",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "J2",
    },
    // Furniture & fittings (bay I2)
    {
      name: "Single Line Tray Trolley (162x68x18cm)",
      sku: "HRFS-025",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Reddish Brown Plywood (868x300x400mm)",
      sku: "HRFS-026",
      unit_of_measure: "unit",
      stock_quantity: 17,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Plywood (896x280x260mm)",
      sku: "HRFS-027",
      unit_of_measure: "unit",
      stock_quantity: 27,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wood Frame Plywood",
      sku: "HRFS-029",
      unit_of_measure: "unit",
      stock_quantity: 11,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Slide Series Light (45#)",
      sku: "HRFS-034",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Flat Wooden Board",
      sku: "HRFS-035",
      unit_of_measure: "unit",
      stock_quantity: 9,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wooden Deck",
      sku: "HRFS-036",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Table Tops / Display Stand",
      sku: "HRFS-058",
      unit_of_measure: "unit",
      stock_quantity: 67,
      low_stock_threshold: 7,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Cushion Chairs",
      sku: "HRFS-059",
      unit_of_measure: "unit",
      stock_quantity: 50,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wooden Locker",
      sku: "HRFS-060",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Stool Chair",
      sku: "HRFS-061",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Centre Table Cover",
      sku: "HRFS-062",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Square Frame",
      sku: "HRFS-063",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Chair Table Cover",
      sku: "HRFS-064",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Square Frame Tops",
      sku: "HRFS-065",
      unit_of_measure: "unit",
      stock_quantity: 43,
      low_stock_threshold: 4,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Rectangle Table Tops",
      sku: "HRFS-066",
      unit_of_measure: "unit",
      stock_quantity: 8,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Circle Table Tops",
      sku: "HRFS-067",
      unit_of_measure: "unit",
      stock_quantity: 12,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Dining/Lounge Chair Green Small (62x59x82cm)",
      sku: "HRFS-085",
      unit_of_measure: "unit",
      stock_quantity: 68,
      low_stock_threshold: 7,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Dining/Lounge Chair Orange Small (62x59x82cm)",
      sku: "HRFS-086",
      unit_of_measure: "unit",
      stock_quantity: 24,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Metal Lantern Big (61x61x42cm)",
      sku: "HRFS-087",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Metal Lantern Small (52x52x58cm)",
      sku: "HRFS-088",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Dining/Lounge Chair Big (87x58x98cm)",
      sku: "HRFS-089",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wooden Chair B04# (142x62x60cm)",
      sku: "HRFS-090",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wooden Chair (117x71x66cm)",
      sku: "HRFS-091",
      unit_of_measure: "unit",
      stock_quantity: 12,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    {
      name: "Wooden Sofa Chair (60x70x72cm)",
      sku: "HRFS-092",
      unit_of_measure: "unit",
      stock_quantity: 12,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "I2",
    },
    // Wall panels (bays K2, L2)
    {
      name: "Teak Wall Panel Indoor (219x26x2901mm)",
      sku: "HRFS-074",
      unit_of_measure: "pc",
      stock_quantity: 1249,
      low_stock_threshold: 125,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "White Wall Panel Indoor (219x26x2902mm)",
      sku: "HRFS-075",
      unit_of_measure: "pc",
      stock_quantity: 850,
      low_stock_threshold: 85,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "Grey Wall Panel Indoor (155x17x2900mm)",
      sku: "HRFS-076",
      unit_of_measure: "pc",
      stock_quantity: 1280,
      low_stock_threshold: 128,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "Black Strings Wall Paper (155x17x2900mm)",
      sku: "HRFS-077",
      unit_of_measure: "pc",
      stock_quantity: 1861,
      low_stock_threshold: 186,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "White Wall Panel Indoor (154x17x2900mm)",
      sku: "HRFS-078",
      unit_of_measure: "pc",
      stock_quantity: 1300,
      low_stock_threshold: 130,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "Red Wall Paper Indoor (154x17x2900mm)",
      sku: "HRFS-079",
      unit_of_measure: "pc",
      stock_quantity: 1480,
      low_stock_threshold: 148,
      unit_cost: null,
      warehouse_location: "K2",
    },
    {
      name: "Black Wall Panel Indoor (219x26x2900mm)",
      sku: "HRFS-073",
      unit_of_measure: "pc",
      stock_quantity: 307,
      low_stock_threshold: 31,
      unit_cost: null,
      warehouse_location: "L2",
    },
    {
      name: "Aluminum Alloy",
      sku: "HRFS-021",
      unit_of_measure: "unit",
      stock_quantity: 557,
      low_stock_threshold: 56,
      unit_cost: null,
      warehouse_location: "L2",
    },
    // Shelving (bay H2)
    {
      name: "Multi-Deck Shelf",
      sku: "HRFS-080",
      unit_of_measure: "unit",
      stock_quantity: 14,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H2",
    },
    {
      name: "No Deck Shelf (Small)",
      sku: "HRFS-081",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H2",
    },
    {
      name: "No Deck Shelf (Long)",
      sku: "HRFS-082",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H2",
    },
    {
      name: "Drawer",
      sku: "HRFS-083",
      unit_of_measure: "unit",
      stock_quantity: 11,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H2",
    },
    {
      name: "Corner Shelf",
      sku: "HRFS-084",
      unit_of_measure: "unit",
      stock_quantity: 11,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "H2",
    },
    // Wall frames (bay P2)
    {
      name: "Wall Frames",
      sku: "HRFS-068",
      unit_of_measure: "unit",
      stock_quantity: 124,
      low_stock_threshold: 12,
      unit_cost: null,
      warehouse_location: "P2",
    },
    // HP Laptops (bay A2)
    {
      name: "HP Laptop",
      sku: "HRFS-093",
      unit_of_measure: "unit",
      stock_quantity: 200,
      low_stock_threshold: 20,
      unit_cost: null,
      warehouse_location: "A2",
    },
    // Deep freezers (bay M1)
    {
      name: "Deep Freezer ZX-2.5ZAJ (2500x830x858mm)",
      sku: "HRFS-069",
      unit_of_measure: "unit",
      stock_quantity: 30,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "M1",
    },
    {
      name: "Deep Freezer ZX-1.9ZAJ (1870x830x850mm)",
      sku: "HRFS-070",
      unit_of_measure: "unit",
      stock_quantity: 32,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "M1",
    },
    {
      name: "Island Freezer (2390x1150x860mm)",
      sku: "HRFS-071",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "M1",
    },
    {
      name: "Deep Freezer (standard)",
      sku: "HRFS-072",
      unit_of_measure: "unit",
      stock_quantity: 5,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "M1",
    },
    {
      name: "Deep Freezers (bulk)",
      sku: "HRFS-096",
      unit_of_measure: "unit",
      stock_quantity: 124,
      low_stock_threshold: 12,
      unit_cost: null,
      warehouse_location: "A1",
    },
    // Misc (bay A1)
    {
      name: "Hisense Outdoor Air Conditioner Units",
      sku: "HRFS-097",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "A1",
    },
    {
      name: "Hisense TV (older models)",
      sku: "HRFS-098",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "A1",
    },
    {
      name: "Shelf Stand Long (Big Size)",
      sku: "HRFS-099",
      unit_of_measure: "unit",
      stock_quantity: 334,
      low_stock_threshold: 33,
      unit_cost: null,
      warehouse_location: "A1",
    },
    {
      name: "Shelf Stand Long (Small Size)",
      sku: "HRFS-100",
      unit_of_measure: "unit",
      stock_quantity: 106,
      low_stock_threshold: 11,
      unit_cost: null,
      warehouse_location: "A1",
    },
    {
      name: "Bedside Stool Furniture",
      sku: "HRFS-101",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "A1",
    },
    {
      name: "HGC Banner Accessories",
      sku: "HRFS-102",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "A1",
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // LABAMBAM — from "LABAMBAM LH WAREHOUSE ITEMS REPORT - STOCK SUMMARY.csv"
  // Only items with Stock Balance > 0 are included
  // ─────────────────────────────────────────────────────────────────────────
  const labambamProducts = [
    // Aisle 1 — Baking ovens & proofing (bay E1)
    {
      name: "Combi Oven 1",
      sku: "LBMB-001",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Combi Oven 2",
      sku: "LBMB-002",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Proofer",
      sku: "LBMB-003",
      unit_of_measure: "unit",
      stock_quantity: 8,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Donut Machine Small",
      sku: "LBMB-004",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Spiral Dough Mixer",
      sku: "LBMB-005",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "3 Deck Convention Oven",
      sku: "LBMB-006",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Rotary Oven",
      sku: "LBMB-007",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    // Aisle 2 — Grills, fryers & small appliances (bay E1)
    {
      name: "Massive Popcorn Machine",
      sku: "LBMB-008",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Gas Grill with Cabinet ZH-TH",
      sku: "LBMB-009",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Gas Grill with Cabinet ZH-TG+TH",
      sku: "LBMB-010",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Gas 2 Tank Fryer with Cabinet JGF-785",
      sku: "LBMB-011",
      unit_of_measure: "unit",
      stock_quantity: 9,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Gas Deep Fryer",
      sku: "LBMB-012",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "4 Burner Gas Cooker EMP.PLS.9FG020-LPG",
      sku: "LBMB-013",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Deep Fryer / Griddle without Cabinet ED 30",
      sku: "LBMB-014",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Counter Top Gas Grill K6013R LPG",
      sku: "LBMB-015",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Electric Fryer / Grill EMP.PLS.71E010",
      sku: "LBMB-016",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Juice Machine",
      sku: "LBMB-017",
      unit_of_measure: "unit",
      stock_quantity: 9,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Empero Small Pizza Oven",
      sku: "LBMB-018",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Cup Sealer",
      sku: "LBMB-019",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Electric Shawarma / Wrap Grill",
      sku: "LBMB-020",
      unit_of_measure: "unit",
      stock_quantity: 5,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Oven Stand EMP.AS.4",
      sku: "LBMB-021",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Commercial Health Blender",
      sku: "LBMB-022",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Juicer A1000",
      sku: "LBMB-023",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Slush Machine",
      sku: "LBMB-024",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Table Top Electric Burner",
      sku: "LBMB-025",
      unit_of_measure: "unit",
      stock_quantity: 9,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Popcorn Machine (Bottom Stand)",
      sku: "LBMB-026",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Popcorn Machine",
      sku: "LBMB-027",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    // Aisle 3 — Showcases, warmers & specialty (bay E1)
    {
      name: "Charcoal Grill EMP.PTG.02",
      sku: "LBMB-028",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Electric Chicken Rotisserie",
      sku: "LBMB-029",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Electric Convection Rotary Oven EMP.EDKF-10",
      sku: "LBMB-030",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Donut Machine Big",
      sku: "LBMB-031",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Small Showcase 1 DH861",
      sku: "LBMB-032",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Small Showcase 2 DH780",
      sku: "LBMB-033",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Small Showcase 3 2018105",
      sku: "LBMB-034",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Small Showcase 4",
      sku: "LBMB-035",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Small Showcase 5 DH524",
      sku: "LBMB-036",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Cabinet Set of 7 (2 White & Black + Triangular Parts)",
      sku: "LBMB-037",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Wall Cabinet PRJ.GST.HARVEST.001",
      sku: "LBMB-038",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Towel Warmer",
      sku: "LBMB-039",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Bubble Tea / Fruit Cold Display",
      sku: "LBMB-040",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Electric Plate Warmer",
      sku: "LBMB-041",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Pressure Pot",
      sku: "LBMB-042",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Chaffing Dish (Round)",
      sku: "LBMB-043",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Palm Street Sebastiano Showcase Glass",
      sku: "LBMB-044",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    {
      name: "Stock Pot 60 x 60",
      sku: "LBMB-045",
      unit_of_measure: "unit",
      stock_quantity: 5,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "E1",
    },
    // Aisle 4 — Ice machines, mixers & sinks (bay F1)
    {
      name: "Ice Cream Machine",
      sku: "LBMB-046",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Machine DH 50",
      sku: "LBMB-047",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Machine DH 150",
      sku: "LBMB-048",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Shaver",
      sku: "LBMB-049",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Maker Small ZQ100",
      sku: "LBMB-050",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Maker ZQ 60 KG",
      sku: "LBMB-051",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Maker ZQ 100 KG",
      sku: "LBMB-052",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Massive Goose Pot",
      sku: "LBMB-053",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Blast Chiller",
      sku: "LBMB-054",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Ice Bin",
      sku: "LBMB-055",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Bread Dough Roller",
      sku: "LBMB-056",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Small Kitchen Counter Cabinet",
      sku: "LBMB-057",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Double Sink (Turkey)",
      sku: "LBMB-058",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Double Sink (China)",
      sku: "LBMB-059",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Overturning Mixer 260L JM-120T",
      sku: "LBMB-060",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Overturning Mixer 200L JM-80T",
      sku: "LBMB-061",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "32CM Frying Pan",
      sku: "LBMB-062",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "34CM Frying Pan",
      sku: "LBMB-063",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Kids Booster Seat",
      sku: "LBMB-064",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Delivery Box",
      sku: "LBMB-065",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    // Aisle 5 — Wine coolers, display, bread equipment (bay F1)
    {
      name: "Showcase Display (Rosegold & Silver)",
      sku: "LBMB-066",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Wine Cooler YC 270",
      sku: "LBMB-067",
      unit_of_measure: "unit",
      stock_quantity: 5,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Wine Cooler YC 710B",
      sku: "LBMB-068",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Wine Cooler YC 188",
      sku: "LBMB-069",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Air Curtain 1200MM",
      sku: "LBMB-070",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Air Curtain 900MM",
      sku: "LBMB-071",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Bread Slicer",
      sku: "LBMB-072",
      unit_of_measure: "unit",
      stock_quantity: 10,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Sealing Machine",
      sku: "LBMB-073",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Dough Sheeter Machine",
      sku: "LBMB-074",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Long Shelves",
      sku: "LBMB-075",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Bar Fridge with Shelving",
      sku: "LBMB-076",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    {
      name: "Meat Grinder",
      sku: "LBMB-077",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F1",
    },
    // Aisle 6 — Bain maries, coffee blenders, scales, heaters (bay G1)
    {
      name: "Bain Marie (Unassembled)",
      sku: "LBMB-078",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Bain Marie (Assembled)",
      sku: "LBMB-079",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Coffee Blender CRM9016",
      sku: "LBMB-080",
      unit_of_measure: "unit",
      stock_quantity: 60,
      low_stock_threshold: 6,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Coffee Blender CRM9012",
      sku: "LBMB-081",
      unit_of_measure: "unit",
      stock_quantity: 73,
      low_stock_threshold: 7,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Coffee Bin C1007",
      sku: "LBMB-082",
      unit_of_measure: "unit",
      stock_quantity: 75,
      low_stock_threshold: 8,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Regular Gas Tall Patio Heater",
      sku: "LBMB-083",
      unit_of_measure: "unit",
      stock_quantity: 16,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Small Scale TCS 150A",
      sku: "LBMB-084",
      unit_of_measure: "unit",
      stock_quantity: 3,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Scale ACS 30A",
      sku: "LBMB-085",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Fructos Machine",
      sku: "LBMB-086",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Printing Scale",
      sku: "LBMB-087",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "ET-KFO3 Smokeless Electric Grill",
      sku: "LBMB-088",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Glass Tube Pyramid Patio Heater",
      sku: "LBMB-089",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Aisle 7 — Disposables & trays (bay G1)
    {
      name: "Disposable CJH 3000",
      sku: "LBMB-090",
      unit_of_measure: "unit",
      stock_quantity: 35,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 2500",
      sku: "LBMB-091",
      unit_of_measure: "unit",
      stock_quantity: 35,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 2000",
      sku: "LBMB-092",
      unit_of_measure: "unit",
      stock_quantity: 35,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 518",
      sku: "LBMB-093",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable 101 QSMF",
      sku: "LBMB-094",
      unit_of_measure: "unit",
      stock_quantity: 34,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 70",
      sku: "LBMB-095",
      unit_of_measure: "unit",
      stock_quantity: 30,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Black Round Trays",
      sku: "LBMB-096",
      unit_of_measure: "unit",
      stock_quantity: 17,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Brown Trays",
      sku: "LBMB-097",
      unit_of_measure: "unit",
      stock_quantity: 110,
      low_stock_threshold: 11,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 600",
      sku: "LBMB-098",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 1200",
      sku: "LBMB-099",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 915",
      sku: "LBMB-100",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 103",
      sku: "LBMB-101",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Disposable CJH 920 (Incomplete)",
      sku: "LBMB-102",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Royal Green Dinner Set (Original Box)",
      sku: "LBMB-103",
      unit_of_measure: "unit",
      stock_quantity: 4,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Royal Green Dinner Set (Changed Box)",
      sku: "LBMB-104",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Aisle 8 — Industrial cookers & outdoor furniture (bay G1 scrap yard)
    {
      name: "Industrial Gas Cooker Single",
      sku: "LBMB-105",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Industrial Gas Cooker Double",
      sku: "LBMB-106",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "Umbrella Base",
      sku: "LBMB-107",
      unit_of_measure: "unit",
      stock_quantity: 15,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G1",
    },
    {
      name: "White Outdoor Table",
      sku: "LBMB-108",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G1",
    },
    // Aisle 10 — Coffee machines, fridges, shelves (bay G2)
    {
      name: "Coffee Machine Wooden Boxes",
      sku: "LBMB-109",
      unit_of_measure: "unit",
      stock_quantity: 20,
      low_stock_threshold: 2,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Coffee Machine CRM 3201",
      sku: "LBMB-110",
      unit_of_measure: "unit",
      stock_quantity: 8,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Coffee Machine CRM 3120C",
      sku: "LBMB-111",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Combination Gas / Charcoal Grill",
      sku: "LBMB-112",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Single Door Fridge EMP.70.80.01",
      sku: "LBMB-113",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Deep Freezer Double Door EMP.70.80.02",
      sku: "LBMB-114",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Food Warmer EMP.BQ1",
      sku: "LBMB-115",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Drawer Warmer EMP.EI.03",
      sku: "LBMB-116",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Food Processor",
      sku: "LBMB-117",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Vacuum Sealer EMP VCM.02",
      sku: "LBMB-118",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Dishwasher",
      sku: "LBMB-119",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Table Top Fridge",
      sku: "LBMB-120",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Bar Fridge",
      sku: "LBMB-121",
      unit_of_measure: "unit",
      stock_quantity: 1,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Kitchen Aluminium Shelves EMP.T.3.36107-18-4",
      sku: "LBMB-122",
      unit_of_measure: "unit",
      stock_quantity: 13,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Small Slim Kitchen Shelves",
      sku: "LBMB-123",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    {
      name: "Knee Operated Basin EMP.DKE.001",
      sku: "LBMB-124",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "G2",
    },
    // Racked section (bay F2) — plates, woks, knives
    {
      name: "750ML Plates",
      sku: "LBMB-125",
      unit_of_measure: "unit",
      stock_quantity: 56,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "100ML Plates",
      sku: "LBMB-126",
      unit_of_measure: "unit",
      stock_quantity: 48,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Waffle Maker",
      sku: "LBMB-127",
      unit_of_measure: "unit",
      stock_quantity: 2,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Knives (Various Sizes)",
      sku: "LBMB-128",
      unit_of_measure: "unit",
      stock_quantity: 33,
      low_stock_threshold: 3,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Metal Woks No Long Handle (Rusted)",
      sku: "LBMB-129",
      unit_of_measure: "unit",
      stock_quantity: 11,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Round Black Trays (Rack)",
      sku: "LBMB-130",
      unit_of_measure: "unit",
      stock_quantity: 48,
      low_stock_threshold: 5,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Metal Woks Long Handle (Various Sizes)",
      sku: "LBMB-131",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Metal Woks No Long Handle (Various Sizes)",
      sku: "LBMB-132",
      unit_of_measure: "unit",
      stock_quantity: 7,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F2",
    },
    {
      name: "Black Pans (Non-stick)",
      sku: "LBMB-133",
      unit_of_measure: "unit",
      stock_quantity: 6,
      low_stock_threshold: 1,
      unit_cost: null,
      warehouse_location: "F2",
    },
  ];

  const allProducts = [...jaraProducts, ...harvestProducts, ...labambamProducts];

  const { data: prodData, error: prodError } = await supabase
    .from("products")
    .insert(allProducts)
    .select();
  if (prodError) throw prodError;
  console.log(`  Inserted ${prodData?.length ?? 0} products`);

  // ── Done ───────────────────────────────────────────────────────────────────
  console.log("\n✓ Seed complete.");
  console.log(`  Default password for all accounts: ${DEFAULT_PASSWORD}`);
  console.log("\n  Users created:");
  console.log("  grace.usoro@harvestgl.net            → ADMIN");
  console.log("  chinedu.ewuzie@harvestgl.net         → WAREHOUSE_MANAGER");
  console.log("  prince.don-ibeh@harvestgl.net        → FINANCE_MANAGER");
  console.log("  chinwe@harvestgl.net                 → FINANCE_MANAGER");
  console.log("  iberedem.ikwo@harvestgl.net          → FINANCE_MANAGER");
  console.log("  bisi@harvestgl.net                   → BU_MANAGER (Bounty)");
  console.log("  oghenetejiri.edje@harvestgl.net      → BU_MANAGER (Jara)");
  console.log("  ugou@harvestgl.net                   → BU_MANAGER (Labambam)");
  console.log("  esomchi.uche@harvestgl.net           → BU_MANAGER (HGC)");
  console.log("  Chigozie@harvestgl.net               → BU_MANAGER (Grand Access)");
  console.log("  newlife@harvestgl.net                → BU_MANAGER (Harvest Retail)");
  console.log("  kingsley@harvestgl.net               → BU_MANAGER (Harvest Retail)");
}

main().catch((err) => {
  console.error("\n✗ Seed failed:", err);
  process.exit(1);
});
