-- Migration: 016_intra_warehouse_transfers.sql
-- Purpose: Internal warehouse asset reassignment.
--   Reassigns ownership of a quantity of a product from the central warehouse pool
--   (or another SBU) to a target SBU. Atomically decrements products.stock_quantity
--   when the transfer completes.
--
--   Intra-warehouse transfers do NOT use the full transfer-request lifecycle —
--   they are direct, single-step operations performed by the Warehouse Manager.

BEGIN;

CREATE TABLE IF NOT EXISTS public.intra_warehouse_transfers (
  id                  uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_number    text          NOT NULL UNIQUE,
  product_id          uuid          NOT NULL REFERENCES public.products(id),
  quantity            integer       NOT NULL CHECK (quantity > 0),
  -- NULL = sourced from the warehouse general pool
  from_sbu_id         uuid          REFERENCES public.sbus(id),
  to_sbu_id           uuid          NOT NULL REFERENCES public.sbus(id),
  transferred_by      uuid          NOT NULL REFERENCES auth.users(id),
  transfer_date       date          NOT NULL DEFAULT CURRENT_DATE,
  status              text          NOT NULL DEFAULT 'COMPLETED'
                                    CHECK (status IN ('PENDING','COMPLETED','CANCELLED')),
  notes               text,
  created_at          timestamptz   NOT NULL DEFAULT now(),
  updated_at          timestamptz   NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.intra_warehouse_transfers IS
  'Direct intra-warehouse asset reassignments. Stock is decremented from products '
  'when status = COMPLETED. Reference format: IWT-YYYY-NNNNN.';

CREATE INDEX IF NOT EXISTS idx_intra_transfers_product   ON public.intra_warehouse_transfers(product_id);
CREATE INDEX IF NOT EXISTS idx_intra_transfers_to_sbu    ON public.intra_warehouse_transfers(to_sbu_id);
CREATE INDEX IF NOT EXISTS idx_intra_transfers_from_sbu  ON public.intra_warehouse_transfers(from_sbu_id);
CREATE INDEX IF NOT EXISTS idx_intra_transfers_date      ON public.intra_warehouse_transfers(transfer_date);

-- ─────────────────────────────────────────────────────────────────────────────
-- RPC: process_intra_transfer
--   Atomically decrement stock and insert the transfer row.
--   Reference number is generated by the caller (API) for consistency with
--   other ref-number patterns (TRF, RTN, SGRN).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.process_intra_transfer(
  p_reference_number text,
  p_product_id       uuid,
  p_quantity         integer,
  p_from_sbu_id      uuid,
  p_to_sbu_id        uuid,
  p_transferred_by   uuid,
  p_notes            text DEFAULT NULL
) RETURNS uuid AS $$
DECLARE
  v_id            uuid;
  v_stock_before  integer;
BEGIN
  IF p_quantity <= 0 THEN
    RAISE EXCEPTION 'process_intra_transfer: quantity must be positive (got %)', p_quantity;
  END IF;

  -- Lock the product row and validate stock
  SELECT stock_quantity INTO v_stock_before
  FROM public.products
  WHERE id = p_product_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'process_intra_transfer: product not found (id: %)', p_product_id;
  END IF;

  IF v_stock_before < p_quantity THEN
    RAISE EXCEPTION 'process_intra_transfer: insufficient stock (available: %, requested: %)',
      v_stock_before, p_quantity;
  END IF;

  -- Decrement warehouse stock
  UPDATE public.products
  SET stock_quantity = stock_quantity - p_quantity,
      updated_at     = now()
  WHERE id = p_product_id;

  -- Record the transfer
  INSERT INTO public.intra_warehouse_transfers (
    reference_number, product_id, quantity,
    from_sbu_id, to_sbu_id, transferred_by, status, notes
  ) VALUES (
    p_reference_number, p_product_id, p_quantity,
    p_from_sbu_id, p_to_sbu_id, p_transferred_by, 'COMPLETED', p_notes
  )
  RETURNING id INTO v_id;

  -- Best-effort audit log
  BEGIN
    INSERT INTO public.audit_logs(entity_type, entity_id, action, performed_by, details, created_at)
    VALUES (
      'intra_warehouse_transfer',
      v_id,
      'create',
      p_transferred_by,
      json_build_object(
        'reference_number', p_reference_number,
        'product_id',       p_product_id,
        'quantity',         p_quantity,
        'from_sbu_id',      p_from_sbu_id,
        'to_sbu_id',        p_to_sbu_id
      ),
      now()
    );
  EXCEPTION WHEN undefined_table THEN
    NULL;
  END;

  RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.intra_warehouse_transfers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "intra_transfers_select"
  ON public.intra_warehouse_transfers FOR SELECT TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') IN (
      'ADMIN', 'WAREHOUSE_MANAGER', 'FINANCE_MANAGER'
    )
    OR
    (
      (auth.jwt() -> 'user_metadata' ->> 'role') IN ('BU_MANAGER', 'UNIT_STAFF')
      AND to_sbu_id::text = (auth.jwt() -> 'user_metadata' ->> 'sbu_id')
    )
  );

CREATE POLICY "intra_transfers_insert"
  ON public.intra_warehouse_transfers FOR INSERT TO authenticated
  WITH CHECK (
    (auth.jwt() -> 'user_metadata' ->> 'role') IN ('ADMIN', 'WAREHOUSE_MANAGER')
  );

COMMIT;
